---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.5
before_install: gem install bundler -v 2.0.1
addons:
  chrome: stable # An essential part of recording videos
before_install:
  # Can't do video recording without codecs
  # Taken from https://gist.github.com/kevinGodell/bd52cd74c8c2d66fb69f108ef223c356
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:mc3man/trusty-media; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y ffmpeg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
  - ffmpeg -hwaccels
